import { useRef, useState } from 'react'
import type { FormEvent } from 'react'
import SecureFormControls from './SecureFormControls'
import { postJson } from '../lib/apiClient'
import type { Language } from '../context/language'

type Kind = 'applicant-questionnaire' | 'new-hire-application'

const blankApplication = () => ({ firstName:'',lastName:'',email:'',phone:'',street:'',city:'',state:'',zip:'',position:'',availableDate:'',workAuthorized:'',age18:'',transportation:'',skills:'',employmentHistory:'',education:'',references:'',availability:'',previouslyWorked:'',desiredCompensation:'',signature:'' })

export default function ApplicationForm({ kind, language }: { kind: Kind; language: Language }) {
  const es = language === 'es'
  const isNewHire = kind === 'new-hire-application'
  const [data, setData] = useState(blankApplication)
  const [consent,setConsent]=useState(false);const[honeypot,setHoneypot]=useState('');const[token,setToken]=useState('');const[resetKey,setResetKey]=useState(0);const[startedAt,setStartedAt]=useState(Date.now);const[status,setStatus]=useState<{type:string;message:string}>({type:'',message:''});const formRef=useRef<HTMLFormElement>(null)
  const set=(key:keyof typeof data,value:string)=>setData((current)=>({...current,[key]:value}))
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!token||!consent){setStatus({type:'error',message:es?'Complete el consentimiento y la verificación de seguridad.':'Please complete privacy consent and the security check.'});return}setStatus({type:'loading',message:es?'Enviando…':'Submitting…'});try{const result=await postJson<object,{message:string}>(`/api/forms/${kind}`,{language,...data,security:{consent,website:honeypot,startedAt,recaptchaToken:token}});setStatus({type:'success',message:result.message});formRef.current?.reset();setData(blankApplication());setConsent(false);setToken('');setHoneypot('');setResetKey((v)=>v+1);setStartedAt(Date.now())}catch(error){setStatus({type:'error',message:error instanceof Error?error.message:'Submission failed.'})}}
  return <form className="modern-form application-form" ref={formRef} onSubmit={submit}>
    <section className="form-section"><div className="form-section-head"><span>01</span><div><p className="eyebrow">{es?'Información personal':'Personal information'}</p><h2>{es?'Empecemos con lo básico.':'Start with the basics.'}</h2></div></div><div className="form-grid two">
      <label>{es?'Nombre':'First name'}<input required maxLength={80} onChange={e=>set('firstName',e.target.value)}/></label><label>{es?'Apellido':'Last name'}<input required maxLength={80} onChange={e=>set('lastName',e.target.value)}/></label><label>Email<input required type="email" maxLength={160} onChange={e=>set('email',e.target.value)}/></label><label>{es?'Teléfono':'Phone'}<input required maxLength={30} onChange={e=>set('phone',e.target.value)}/></label><label className="span-2">{es?'Dirección':'Street address'}<input maxLength={160} onChange={e=>set('street',e.target.value)}/></label><label>{es?'Ciudad':'City'}<input maxLength={80} onChange={e=>set('city',e.target.value)}/></label><label>{es?'Estado':'State'}<input maxLength={40} onChange={e=>set('state',e.target.value)}/></label><label>ZIP<input maxLength={12} onChange={e=>set('zip',e.target.value)}/></label>
    </div></section>
    <section className="form-section"><div className="form-section-head"><span>02</span><div><p className="eyebrow">{es?'Trabajo':'Employment'}</p><h2>{isNewHire?(es?'Detalles de incorporación':'Onboarding details'):(es?'Preferencias y disponibilidad':'Preferences & availability')}</h2></div></div><div className="form-grid two">
      <label>{es?'Puesto deseado':'Position'}<input required maxLength={120} onChange={e=>set('position',e.target.value)}/></label><label>{es?'Fecha disponible':'Available date'}<input type="date" onChange={e=>set('availableDate',e.target.value)}/></label><label>{es?'¿Autorizado para trabajar en EE. UU.?':'Authorized to work in the U.S.?'}<select required onChange={e=>set('workAuthorized',e.target.value)}><option value="">—</option><option>Yes / Sí</option><option>No</option></select></label><label>{es?'¿Tiene 18 años o más?':'Are you 18 or older?'}<select required onChange={e=>set('age18',e.target.value)}><option value="">—</option><option>Yes / Sí</option><option>No</option></select></label><label>{es?'Transporte confiable':'Reliable transportation'}<select onChange={e=>set('transportation',e.target.value)}><option value="">—</option><option>Yes / Sí</option><option>No</option></select></label><label>{es?'Disponibilidad / turnos':'Availability / shifts'}<input maxLength={240} onChange={e=>set('availability',e.target.value)}/></label>{isNewHire&&<><label>{es?'¿Trabajó antes con BZ?':'Previously worked with BZ?'}<input maxLength={120} onChange={e=>set('previouslyWorked',e.target.value)}/></label><label>{es?'Compensación deseada':'Desired compensation'}<input maxLength={80} onChange={e=>set('desiredCompensation',e.target.value)}/></label></>}
    </div></section>
    <section className="form-section"><div className="form-section-head"><span>03</span><div><p className="eyebrow">{es?'Experiencia':'Experience'}</p><h2>{es?'Cuéntenos sobre su experiencia.':'Tell us about your background.'}</h2></div></div><label>{es?'Habilidades y certificaciones':'Skills & certifications'}<textarea rows={5} maxLength={2500} onChange={e=>set('skills',e.target.value)}/></label><label>{es?'Historial de empleo':'Employment history'}<textarea rows={7} maxLength={4000} placeholder={es?'Empresa, puesto, fechas, responsabilidades y motivo de salida.':'Company, position, dates, responsibilities and reason for leaving.'} onChange={e=>set('employmentHistory',e.target.value)}/></label><label>{es?'Educación / capacitación':'Education / training'}<textarea rows={4} maxLength={2500} onChange={e=>set('education',e.target.value)}/></label><label>{es?'Referencias profesionales':'Professional references'}<textarea rows={4} maxLength={2500} onChange={e=>set('references',e.target.value)}/></label></section>
    <section className="form-section"><div className="form-section-head"><span>04</span><div><p className="eyebrow">{es?'Certificación':'Certification'}</p><h2>{es?'Revise y firme.':'Review & sign.'}</h2></div></div><p className="form-legal">{es?'Certifico que la información proporcionada es verdadera y completa según mi leal saber y entender. Entiendo que BZ Resources puede verificar la información relacionada con el empleo según lo permita la ley. Los documentos confidenciales de identidad, impuestos, salud y banco no deben enviarse por este formulario.':'I certify that the information provided is true and complete to the best of my knowledge. I understand BZ Resources may verify employment-related information as permitted by law. Sensitive identity, tax, medical and banking documents should not be submitted through this form.'}</p><label>{es?'Firma escrita (nombre completo)':'Typed signature (full name)'}<input required maxLength={160} onChange={e=>set('signature',e.target.value)}/></label><SecureFormControls language={language} consent={consent} honeypot={honeypot} onConsentChange={setConsent} onHoneypotChange={setHoneypot} onTokenChange={setToken} resetKey={resetKey}/>{status.message&&<p className={`form-message ${status.type}`} role="status">{status.message}</p>}<button className="button form-submit" disabled={status.type==='loading'}>{status.type==='loading'?(es?'Enviando…':'Submitting…'):(es?'Enviar formulario':'Submit Form')}</button></section>
  </form>
}
